-- Active: 1735920129577@@127.0.0.1@3306@culturadebarrio_db
-- CREATE DATABASE culturadebarrio_db 
--     CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci;

-- Tabla LOCATIONS
CREATE TABLE LOCATIONS (
    loc_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    loc_name VARCHAR(100) NOT NULL
);

-- Tabla REQUIREMENTS
CREATE TABLE REQUIREMENTS (
    req_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    req_name VARCHAR(30) NOT NULL
);

-- Tabla CATEGORIES
CREATE TABLE CATEGORIES (
    cat_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cat_name VARCHAR(200) NOT NULL
);

-- Tabla USERS
CREATE TABLE USERS (
    user_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(100) NOT NULL,
    user_lastname VARCHAR(100) NOT NULL,
    user_mail VARCHAR(200) NOT NULL UNIQUE,
    user_password VARCHAR(100) NOT NULL,
    user_phoneNumber BIGINT NOT NULL UNIQUE,
    fk_loc INT NOT NULL,
    user_biography VARCHAR(200),
    user_age INT NOT NULL,
    user_registerDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (fk_loc) REFERENCES LOCATIONS(loc_id)
);

-- Tabla EVENTS
CREATE TABLE EVENTS (
    evt_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    evt_tittle VARCHAR(40) NOT NULL,
    evt_duraction INT NULL,
    FK_creator INT NOT NULL,
    evt_description VARCHAR(300) NOT NULL,
    evt_price INT,
    evt_capacity INT,
    fk_loc INT NOT NULL,
    evt_registerDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FK_creator) REFERENCES USERS(user_id),
    FOREIGN KEY (fk_loc) REFERENCES LOCATIONS(loc_id)
);

-- Tabla PARTICIPANTS
CREATE TABLE PARTICIPANTS (
    prt_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_user INT NOT NULL,
    FK_evt INT NOT NULL,
    FOREIGN KEY (FK_user) REFERENCES USERS(user_id),
    FOREIGN KEY (FK_evt) REFERENCES EVENTS(evt_id)
);

-- Tabla QUESTIONS
CREATE TABLE QUESTIONS (
    qst_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_sender INT NOT NULL,
    FK_evt INT NOT NULL,
    qst_message VARCHAR(100) NOT NULL,
    qst_registerDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FK_sender) REFERENCES USERS(user_id),
    FOREIGN KEY (FK_evt) REFERENCES EVENTS(evt_id)
);

-- Tabla ANSWERS
CREATE TABLE ANSWERS (
    ans_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ans_message VARCHAR(150) NOT NULL,
    FK_qst INT NOT NULL,
    FOREIGN KEY (FK_qst) REFERENCES QUESTIONS(qst_id)
);

-- Tabla EVENT_REQUIREMENT
CREATE TABLE EVENT_REQUIREMENT (
    evtReq_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_evt INT NOT NULL,
    FK_req INT NOT NULL,
    FOREIGN KEY (FK_evt) REFERENCES EVENTS(evt_id),
    FOREIGN KEY (FK_req) REFERENCES REQUIREMENTS(req_id)
);

-- Tabla CATEGORY_EVENT
CREATE TABLE CATEGORY_EVENT (
    catEvt_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FK_cat INT NOT NULL,
    FK_evt INT NOT NULL,
    FOREIGN KEY (FK_cat) REFERENCES CATEGORIES(cat_id),
    FOREIGN KEY (FK_evt) REFERENCES EVENTS(evt_id)
);